Hw12 13 14 15 calendar http grpc
ids79/otus_go_homework pull request #14
Opened 2023-12-26 11:28 UTC by ids79

2024-01-12 05:53 UTC, dshemin requested changes

2024-01-12 05:53 UTC, dshemin commented on hw12_13_14_15_calendar/Makefile
> +	rm -rf internal/pb
Критично:

Обратите внимание на задание:
```
добавить в Makefile команду `generate`; `make generate` - вызывает `go generate`, которая в свою очередь
генерирует код GRPC сервера на основе Protobuf спецификаций;
```

2024-01-12 05:53 UTC, dshemin commented on hw12_13_14_15_calendar/api/EventService.proto
> +  rpc ListOnMonth (Request) returns (Events) {}
Важно:

В Request я могу передать uuid или date. Соответственно в данные методы я могу передать uuid и что тогда метод должен мне вернуть? Есть неопределённость в поведении, что нехорошо.

2024-01-12 05:53 UTC, dshemin commented on hw12_13_14_15_calendar/api/EventService.proto
> +    string resalt = 1;
Совет:

`result`

2024-01-12 05:53 UTC, dshemin commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +			os.Exit(1)
Важно:

os.Exit немедленно завершит работу и в итоге соединения по http будут обрублены и не обработаны.

2024-01-12 05:53 UTC, dshemin commented on hw12_13_14_15_calendar/internal/app/app.go
> +		a.logg.Error("error with adding an event: ", err)
Важно:

Если мы не сохраним событие, то мы всё равно вернём uuid. И как тогда вызвающий код поймёт что мы не сохранили событие?

Данная проблема есть во всех методах.

2024-01-12 05:53 UTC, dshemin commented on hw12_13_14_15_calendar/internal/app/app.go
> +		return make([]Event, 0)
Важно:

Нет нужды выделять память по слайс, можно вернуть nil.

2024-01-12 05:53 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/grpc/middleware.go
> +	p, _ := peer.FromContext(ctx)
Важно:

Игнорирование второго параметра. Он сигнализирует о том, есть peer или нет. Если не проверять, то можем получить попытку разыменования nil и панику.

2024-01-12 05:53 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/grpc/server.go
> +		s.logg.Error(err)
Важно:

Если не смогли создать listener то мы просто залогируем ошибку и попробуем использовать его при поднятии сервера. И, в итоге, получим скорее всего ошибку там. О которой тоже никого не предупредим.

Всегда возвращайте ошибку из функций, а не логируйте!

2024-01-12 05:53 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/grpc/server.go
> +	return &pb.Responce{Resalt: "error with adding an event"}, nil
Важно:

Т.е. чтобы клиенту понять была ошибка или нет, ему надо будет проверять что в result лежит валидный uuid. А что если мы поменяем идентификаторы на другое представление, не uuid а например на рандомную строку? Как тогда клиенту понять что была ошибка?

Не пытайтесь использовать один параметр для передачи разных по смыслу вещей. Пусть будет два поля uuid и error

2024-01-12 05:53 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/http/marshal.go
> +	if err != nil {
Важно:

Если не добавляете контекст, то просто:
```
return json.Marshal(st)
```

2024-01-12 05:53 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/http/marshal.go
> +	if err != nil {
Важно:

Если не добавляете контекст, то просто:
```
return json.Marshal(st)
```

2024-01-12 05:53 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +	st.conn, err = sqlx.Connect("pgx", st.connStr)
Важно:

Верните пожалуйста контекст. Все операции, которые могут занять некоторое время, лучше делать с контекстом чтобы иметь возможность контролировать.

2024-01-12 05:53 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +	if err := goose.Down(st.conn.DB, "migrations"); err != nil {
Важно:

Зачем нам убивать миграции во время остановки стораджа?

2024-01-12 05:53 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/types/types.go
> +var ErrDeteIsOccupied = errors.New("the current date and time is occupied by another event")
Совет:

`ErrDateIsOccupied`

2024-01-12 05:53 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +	query := `select * from events where id = $1`
Важно:

Зачем делать селект перед удалением?

2024-01-13 14:37 UTC, ids79 commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +	query := `select * from events where id = $1`
Я проверяю, если записи нет, выдаю ошибку ErrNotExistUUID.
Для этого выполняю предварительный select

2024-01-13 14:41 UTC, ids79 commented on hw12_13_14_15_calendar/internal/app/app.go
> +		a.logg.Error("error with adding an event: ", err)
Если произошла ошибка при добавлении записи в u будет nil:
func (st *Storage) Create(ctx context.Context, ev types.Event) (uuid.UUID, error) {
	query := `select * from events where date_time = $1`
	rows, err := st.conn.QueryContext(ctx, query, ev.DateTime)
	if err != nil {
		return uuid.Nil, err
	}
	if rows.Next() {
		return uuid.Nil, types.ErrDateIsOccupied
	}
	u := uuid.NewV4()
	y, m, d := ev.DateTime.Date()
	_, w := ev.DateTime.ISOWeek()
	query = `insert into events
	(id, title, description, date_time, year, month, week, day, duration, user_id, time_before) 
	values($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)`
	_, err = st.conn.ExecContext(ctx, query,
		u.String(), ev.Title, ev.Description, ev.DateTime, y, int(m), w, d, int(ev.Duration), ev.UserID, int(ev.TimeBefore))
	if err != nil {
		return uuid.Nil, err
	}
	return u, nil
}
Он проверяется, и выдается сообщение об ошибки при добавлении события.

2024-01-13 14:42 UTC, ids79 commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +	query := `select * from events where id = $1`
Вернул ошибку явно:
	if err != nil {
		a.logg.Error("error with adding an event: ", err)
		return uuid.Nil
	}

2024-01-13 14:42 UTC, ids79 commented on hw12_13_14_15_calendar/internal/app/app.go
> +		a.logg.Error("error with adding an event: ", err)
Вернул ошибку явно:
if err != nil {
a.logg.Error("error with adding an event: ", err)
return uuid.Nil
}

2024-01-15 09:01 UTC, ids79 commented on hw12_13_14_15_calendar/Makefile
> +	rm -rf internal/pb
Исправил

2024-01-15 09:01 UTC, ids79 commented on hw12_13_14_15_calendar/api/EventService.proto
> +  rpc ListOnMonth (Request) returns (Events) {}
Исправил

2024-01-15 09:01 UTC, ids79 commented on hw12_13_14_15_calendar/api/EventService.proto
> +    string resalt = 1;
Исправил

2024-01-15 09:01 UTC, ids79 commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +			os.Exit(1)
Исправил

2024-01-15 09:02 UTC, ids79 commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +			os.Exit(1)
Использую sync.WaitGroup чтобы дождаться завершения закрытия серверов и подключения к базе.

2024-01-15 09:02 UTC, ids79 commented on hw12_13_14_15_calendar/internal/server/http/marshal.go
> +	if err != nil {
Исправил

2024-01-15 09:02 UTC, ids79 commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +	st.conn, err = sqlx.Connect("pgx", st.connStr)
Исправил

2024-01-15 09:03 UTC, ids79 commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +	if err := goose.Down(st.conn.DB, "migrations"); err != nil {
Рудимент, убрал

2024-01-15 09:03 UTC, ids79 commented on hw12_13_14_15_calendar/internal/storage/types/types.go
> +var ErrDeteIsOccupied = errors.New("the current date and time is occupied by another event")
Исправил

2024-01-17 01:20 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +	query := `select * from events where id = $1`
В большинстве случаев не имеет смысла делать такую проверку. Мы и так хотим чтобы записи небыло.

2024-01-17 02:09 UTC, dshemin approved these changes

2024-01-17 02:09 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/grpc/middleware.go
> +	p, _ := peer.FromContext(ctx)
Обратите внимание на данный комментарий

2024-01-17 02:09 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/grpc/server.go
> +		s.logg.Error(err)
Обратите внимание на данный комментарий.

2024-01-20 05:17 UTC, dshemin approved these changes

2024-01-20 08:46 UTC, merged