HW12 Int test
ids79/otus_go_homework pull request #16
Opened 2024-01-28 17:09 UTC by ids79

2024-01-28 17:26 UTC, ids79 commented
tester     | ok         github.com/ids79/otus_go_homework/hw12_13_14_15_calendar/tests  19.069s
tester exited with code 0

2024-02-01 01:59 UTC, dshemin requested changes

2024-02-01 01:59 UTC, dshemin commented on hw12_13_14_15_calendar/build/Dockerfile_calendar
> +# Собираем в гошке
Совет:

Если дать имя "calendar.dockerfile" то будет работать подстветка кода.

2024-02-01 01:59 UTC, dshemin commented on hw12_13_14_15_calendar/deployments/docker-compose.yml
> +    depends_on:
Важно:

Дублирование секций depends_on.

2024-02-01 01:59 UTC, dshemin commented on hw12_13_14_15_calendar/docker-compose.yml
> +    depends_on:
Важно:

Тут тоже дублируется секция depends_on

2024-02-01 01:59 UTC, dshemin commented on hw12_13_14_15_calendar/tests/integracion_test.go
> +		js, _ := json.Marshal(ev)
Важно:

Игнорируются ошибки. Потом, если что-то пойдёт не так, понять где именно сломался тест - не получится.

2024-02-01 01:59 UTC, dshemin commented on hw12_13_14_15_calendar/tests/integracion_test.go
> +		if evRem == nil {
Важно:

Зачем, мы выше проверяем что не nil?

2025-08-27 12:22 UTC, merged