HW5 is completed
ids79/otus_go_homework pull request #5
Opened 2023-01-15 13:19 UTC by ids79

## Домашнее задание №5 «Параллельное исполнение»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - run.go ~55 строк

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-01-15 13:37 UTC, dshemin requested changes

2023-01-15 13:37 UTC, dshemin commented on hw05_parallel_execution/run.go
> +func worcker(t Task) {
Совет:

Очепятка `worker`

2023-01-15 13:37 UTC, dshemin commented on hw05_parallel_execution/run.go
> +var chTask chan Task
Важно:

В текущей реализации, если я запущу функцию Run более одного раза параллельно они будут аффектить друг друга и задачи для одного Run будут в другом. Не забывайте, вы пишите библиотечную функцию.

2023-01-15 13:37 UTC, dshemin commented on hw05_parallel_execution/run.go
> +	defer func() {
Критично:

Переусложненно! Вам нужно было сделать простую вещь:

1. Запустить n горутин, каждая из которых должна читать из одного и того же канала
2. Итерироваться по слайсу задач и отправлять в канал.

2023-01-15 13:37 UTC, dshemin commented on hw05_parallel_execution/run.go
> +func Run(tasks []Task, n, m int) (err error) {
Важно:

Что случится если n <= 0 ?

2023-01-15 13:37 UTC, dshemin commented on hw05_parallel_execution/run.go
> +	defer atomic.AddInt32(&working, -1)
Важно:

А не сделали ли вы тут свой вариант sync.WaitGroup? Посмотрите, возможно он решит проблему.

2023-01-15 13:37 UTC, dshemin commented on hw05_parallel_execution/run.go
> +	for {
Важно:

```
for {
  v, ok := <-ch
  if !ok {
     break
  }
  processing(v)
}
```

и

```
for v := range ch {
    processing(v)
}
```

Делают одно и тоже, только второй код более компактный и легче воспринимается.

2023-01-15 13:37 UTC, dshemin commented on hw05_parallel_execution/run.go
> +	err := t()
Важно:

Не понял, зачем тут делаем обработку одной задачи, а потом берёмся обрабатывать канал? Почему не можем сразу начать обрабатывать канал?

2023-01-15 13:45 UTC, ids79 commented on hw05_parallel_execution/run.go
> +	for {
Да, я знаю. В следующей варианте использую этот вариант

2023-01-15 13:46 UTC, ids79 commented on hw05_parallel_execution/run.go
> +	defer atomic.AddInt32(&working, -1)
Да, я так и понял. Сделал первый вариант так. Во втором буду использовать sync.WaitGroup

2023-01-15 13:50 UTC, ids79 commented on hw05_parallel_execution/run.go
> +	err := t()
Ну у меня логика такая: Создаем горутину, назначаем ей задачу (она будет выполнятся первой) Далее, если некоторые горутины завершают работу, создаем новые. А канал уже используем для следующих задач.

2023-01-15 13:51 UTC, ids79 commented on hw05_parallel_execution/run.go
> +	defer func() {
А как на счет создания новых горутин, если некоторые завершились с ошибками?

2023-01-15 13:52 UTC, dshemin commented on hw05_parallel_execution/run.go
> +	err := t()
Создание горутин - дёшево, но не бесплатно. Более правильней, создать сразу нужное количество задач и распределить нагрузку между ними, как я указал в критичном замечании. Я же попросил обратить внимание на него в первую очередь.

2023-01-15 13:57 UTC, dshemin commented on hw05_parallel_execution/run.go
> +	defer func() {
Гортина != задача. Посмотрите на код ниже:

```
tasksCh := make(chan Task)
errsCh := make(chan error)

for i := 0; i < n; i ++ {
  go func() {
       for t := range tasksCh {
           err := t()
           if err != nil {
               errsCh <- err
           }
       }
  }()
}
```

Вот, по сути это решение всей задачи. Надо просто создать несколько воркеров и распределить нагрузку между ними. Естественно тут надо добавить завершение работы задач если у нас количество ошибок превысило `m`, заполнять канал задач и т.п.

2023-01-15 14:01 UTC, ids79 commented on hw05_parallel_execution/run.go
> +func Run(tasks []Task, n, m int) (err error) {
Поставил проверку, добавил тест

2023-01-15 14:03 UTC, ids79 commented on hw05_parallel_execution/run.go
> +func worcker(t Task) {
Исправил

2023-01-15 14:06 UTC, ids79 commented on hw05_parallel_execution/run.go
> +var chTask chan Task
А как тогда нужно сделать? Создавать локальные переменные и передавать их в функции горутин в качестве параметров?

2023-01-15 14:08 UTC, ids79 commented on hw05_parallel_execution/run.go
> +	defer func() {
Я все-таки рассматриваю вариант с запуском дополнительных горутин, чтобы достичь парогового значения количества ошибок, если оно больше чем число одновременно работающих потоков.

2023-01-15 14:26 UTC, ids79 commented on hw05_parallel_execution/run.go
> +	defer atomic.AddInt32(&working, -1)
Не понятно, как используя sync.WaitGroup проверять, сколько одновременно горутин работает в текущий момент...

2023-01-15 16:13 UTC, dshemin approved these changes

2023-01-15 16:13 UTC, dshemin commented on hw05_parallel_execution/run.go
> +	if n <= 0 {
Важно:

На момент проверки мы уже запустили какую-то горутину, выделили память и т.п. Но в итоге мы всё это сделали зря, потому что n <= 0. Всю валидацию входных аргументов надо делать в самом начале функции.

2023-01-15 16:13 UTC, dshemin commented on hw05_parallel_execution/run.go
> +		for {
Важно:

```
for range chErrr {
   m--
}
```

Короче и более читаема.

2023-01-15 16:13 UTC, dshemin commented on hw05_parallel_execution/run.go
> +		wg.Add(1)
Важно:

Сначала wg.Add потом горутина.

2023-01-15 16:13 UTC, dshemin commented on hw05_parallel_execution/run.go
> +			select {
Критично:

Представьте ситуацию, у нас 3 воркера и 100 задач. Задачи долгие по 5 секунд каждая. Вот мы получили первую задачу и её взял первый, вторую - второй. Третью - третий. При попытке записать 4-ую задачу, мы положим её в буфер. А при попытке записать 5-ую задачу - выбросим её, тоже самое мы сделаем и с остальными задачами, скорее всего всем, ведь итерация по циклу закончится всяко быстрее чем за 5 секунд.

В итоге мы выполним только 4 задачи из 100. %-ую из-за того, что она в буфер попала.

2023-01-15 16:14 UTC, dshemin requested changes

2023-01-15 16:14 UTC, dshemin commented on hw05_parallel_execution/run_test.go
> +		require.Truef(t, errors.Is(err, ErrNoThreadsForExecute), "actual err - %v", err)
Важно:

Есть функция require.ErrorIs.

2023-01-15 16:29 UTC, ids79 commented on hw05_parallel_execution/run.go
> +			select {
Не согласен. Прирощение цикла происходит только в момент, когда мы можем записать в канал. Мы будем продолжать итерироваться по циклу пока не выполним все задачи. Ну или порог ошибок не перейдем: 
for i := 0; i < len(tasks); {
		select {
		case <-chErr:
			m--
		default:
			if m == 0 {
				close(chTask)
				return
			}
			select {
			case chTask <- tasks[i]:
				i++
			default:
			}
		}
	}

2023-01-15 16:32 UTC, ids79 commented on hw05_parallel_execution/run_test.go
> +		require.Truef(t, errors.Is(err, ErrNoThreadsForExecute), "actual err - %v", err)
Исправлю

2023-01-15 16:35 UTC, ids79 commented on hw05_parallel_execution/run.go
> +	if n <= 0 {
Но у меня же как раз проверка выполняется до запуска горутин...
	if n <= 0 {
		err = ErrNoThreadsForExecute
		return
	}
	if n > len(tasks) {
		n = len(tasks)
	}
	for i := 0; i < n; i++ {
		wg.Add(1)
		go func() {

2023-01-15 16:48 UTC, dshemin requested changes

2023-01-15 16:48 UTC, dshemin commented on hw05_parallel_execution/run.go
> +	if n <= 0 {
А горутина выше? А выделение памяти под `wg`, `chTask`, `chErr`? Это логично сначала проверить что всё правильно а потом начинать что-то делать!

2023-01-15 16:48 UTC, dshemin commented on hw05_parallel_execution/run.go
> +		wg.Add(1)
Обратите внимание на этот комментарий.

2023-01-15 16:48 UTC, dshemin commented on hw05_parallel_execution/run.go
> +			select {
Окей, тогда объясните зачем такой сложный и запутанный код если можно просто сделать

```
chTask <- tasks[i]
```

Более того цикл будет работать из раза в раз обрабатывая один и тот же элемент без причины нагружая процессор и блокируя системный тред, который в это время может что-то делать!

2023-01-17 16:02 UTC, dshemin approved these changes

2023-01-17 16:02 UTC, dshemin commented on hw05_parallel_execution/run.go
> +	wg := &sync.WaitGroup{}
Важно:

Объявляйте, инициализируйте переменные там, где они реально начнут использоваться.

2023-01-17 16:02 UTC, dshemin commented on hw05_parallel_execution/run.go
> +		for {
Важно:

Можно просто
```
select {
    case <-chErr:
       m--
       if m  <= 0 {
             return
       }
    case chTask <- task:
}
```

2023-01-17 16:02 UTC, dshemin commented on hw05_parallel_execution/run.go
> +	defer func() {
Важно:

Нет нужды делать это в defer'е.

Условно ваш код должен выглядеть так:

```
регистрируем очередь
стартуем воркеры
отправляем задачи в очередь и проверяем что не превысили порог
закрываем очередь задач
ждём пока все воркеры завершаться
закрываем очередь ошибок
Если ошибок больше положенного, то возвращаем ошибку, иначе всё хорошо.
```

2023-01-17 16:12 UTC, ids79 commented on hw05_parallel_execution/run.go
> +		for {
Имеете в виду вот так:
	for _, task := range tasks {
              select {
                    case <-chErr:
                          m--
                          if m  <= 0 {
                                return
                          }
                   case chTask <- task:
              }
	}
Так же не будет работать корректно. Если кейс с ошибкой выполниться, задача не запишется в канал. Или я не прав?
Я сделал такой сложный цикл, чтобы иметь возможность обработать все сообщения об ошибках на каждой итерации цикла и не запустить лишних задач, если число ошибок превысит лимит.

2023-01-17 16:56 UTC, merged