HW6 is completed
ids79/otus_go_homework pull request #6
Opened 2023-01-25 19:00 UTC by ids79

## Домашнее задание №6 «Пайплайн»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - pipeline.go ~55 строк

### Критерии оценки
- [ ] CI-пайплайн зелёный - 5 баллов
- [ ] Добавлены новые юнит-тесты - до 2 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2023-01-27 06:43 UTC, dshemin requested changes

2023-01-27 06:43 UTC, dshemin commented on hw06_pipeline_execution/pipeline.go
> +var Done int32
Важно:

Из-за того, что мы используем глобальную переменную мы свяжем выполнение всех вызовов этой функции. Т.е. если я, в своей программе конкурентно запущу 2 и более раз эту функцию - у меня будут неприятные сюрпризы.

Более того, из-за того что переменная публичная, я могу управлять ей из других пакетов что может нарушить логику работы.

2023-01-27 06:43 UTC, dshemin commented on hw06_pipeline_execution/pipeline.go
> +func ExecutePipeline(in In, done In, wg *sync.WaitGroup, stages ...Stage) Out {
Критично:

В задании сказано:

> Нельзя менять сигнатуры исходных функций.

2023-01-27 06:43 UTC, dshemin commented on hw06_pipeline_execution/pipeline.go
> +					atomic.AddInt32(&Done, 1)
Критично:

А как это повлияет на прекращение работы стейджей?

Более того, можно избежать всего этого кода, если вспомнить свойства канала. Например, посмотрите на данный код и объясните почему он работает.

 ```
 package main

import "fmt"

func main() {
	fmt.Println("start")
	stop := make(chan struct{})
	finished := make(chan struct{})

	go func() {
		foo(stop)
		close(finished)
	}()

	close(stop)
	<-finished
	fmt.Println("finished")
}

func foo(c <-chan struct{}) {
	fmt.Println("lock")
	<-c
	fmt.Println("unlock")
}
 ```

2023-01-27 07:43 UTC, ids79 commented on hw06_pipeline_execution/pipeline.go
> +					atomic.AddInt32(&Done, 1)
Данный пример понятен. но как это применить в данном задании?
Передать стоп - канал в стейдж мы не можем, так как нельзя менять сигнатуру функции (хотя это был бы идеальный вариант).
Первое что я пытался сделать, это в случае получения сигнала Done вычитывал принудительно все из каналов чтобы стейджи завершились. Но это не дало мне необходимой скорости выполнения при завершении.
По этому я прибегнул к глобальной переменной, хотя это мне не нравиться. 
Но какая еще есть возможность завершить стейджи быстро без передачи в них дополнительного стоп канала?

2023-01-27 07:43 UTC, ids79 commented on hw06_pipeline_execution/pipeline.go
> +func ExecutePipeline(in In, done In, wg *sync.WaitGroup, stages ...Stage) Out {
Это рудемент. Он не используется, удалю его.

2023-01-27 11:47 UTC, dshemin requested changes

2023-01-27 11:47 UTC, dshemin commented on hw06_pipeline_execution/pipeline.go
> +					atomic.AddInt32(&Done, 1)
Тут есть два варианта:
1. Обернуть каналы, которые передаются между стейджами.
2. Обернуть запуск каждого стейджа.

2023-01-31 07:52 UTC, dshemin approved these changes

2023-01-31 07:52 UTC, merged